import type { Metadata } from "next";
import "../css/globals.css";
import {ThemeModeScript } from "flowbite-react";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html suppressHydrationWarning>
      <head>
        <ThemeModeScript />
    
      </head>
      <body>{children}</body>
    </html>
  );
}
